### ISSUE TITLE
Bug unknown type 'SDLButtonNames' 

### ISSUE THREAD

**Issue by TobyKLight** [heavy-d/VL.GameController#1]
![GamePadBug](https://user-images.githubusercontent.com/4467208/226024175-e40dd4be-ec68-4e45-8b36-47e769db2d22.JPG)

When I run this I get a bug in the class GameController with an unknown type on a pad 'SDLButtonNames'. 
Changing the type to 'GamePadButton' fixes it for me. 

Same type error also appears in the 'GetButton' process
Finally the helppatch has some ioboxes with the 'SDLButtonNames' type. 

I would submit a PR but seems like there is maybe a reason for this? 

I'm on vvvv 5.0-577 (Have not updated to latest previews because of issues with Fuse)

**Comment by TobyKLight** [comment]
Actually it seems like this approach prevents the thumbsticks being recognised so I guess that's the purpose of the SDLButtonNames type? 

Where is SDLButtonNames meant to come from?

**Comment by heavy-d** [comment]
I just tested with vvvv gamma 2022.5.0-0692 and vvvv gamma 2022.5.0-0456 - both working.
But then I realized that the GameControllerInput.dll might not be found on other computers.

Made a commit that should fix it, so check if that dependency in VL.GameController is found.
Let me know if it is working!

**Comment by heavy-d** [comment]
> Where is SDLButtonNames meant to come from?

The dll provides the enum names for the SDLButtonNames.
So it should look like this:
![image](https://user-images.githubusercontent.com/3121000/226040165-169605c7-aaaf-4daf-b08a-7d50f083e2a8.png)

**Comment by TobyKLight** [comment]
I downloaded the latest repo but still not getting this dll 

This is the location of the dll in the VL.GameController.vl file 
![image](https://user-images.githubusercontent.com/4467208/226207205-57b2be56-8898-409b-aa11-fea088b1ced1.png)

But there is no \bin folder in the repo as I see it
 
![image](https://user-images.githubusercontent.com/4467208/226207277-2460c2fe-0ab8-45d8-b818-c38a5033d8be.png)



Personally I'm not using visual studio with vvvv at the moment so I'm not sure how this kind of distribution is meant to work.

**Comment by heavy-d** [comment]
Oh, that folder was .gitignored - thanks for checking!

**Comment by TobyKLight** [comment]
Fixed now! thanks
